# Generated by Django 3.2.14 on 2022-07-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=16)),
                ('Category', models.CharField(max_length=16)),
                ('tags', models.CharField(max_length=16)),
                ('content', models.TextField()),
            ],
        ),
    ]
